#binary_diff_module/docker-compose.yml


version: "3"
services:
  ghidra-decompiler:
    image: cincan/ghidra-decompiler
    volumes:
      - ./input_binaries:/bin_app/input_binaries
      - ./output:/output

  radiff:
    build:
      context: .
      dockerfile: Dockerfile.radiff
    volumes:
      - ./input_binaries:/bin_app/input_binaries
      - ./output:/output
    entrypoint: []
    command: []
