# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: ghidra-decompiler-job
# spec:
#   template:
#     metadata:
#       labels:
#         app: ghidra-decompiler
#     spec:
#       containers:
#         - name: ghidra-decompiler
#           image: cincan/ghidra-decompiler:latest
#           args:
#             - "decompile"
#             - "/app/input_binaries/binary1.bin"
#           volumeMounts:
#             - name: input-output-storage
#               mountPath: /app/input_binaries
#               subPath: input_binaries
#             - name: input-output-storage
#               mountPath: /output
#               subPath: output
#       restartPolicy: Never
#       volumes:
#         - name: input-output-storage
#           persistentVolumeClaim:
#             claimName: input-output-pvc
