version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - webhook-creator
      - webhook-receiver
    networks:
      - webnet

  webhook-creator:
    build: ./webhook-creator
    environment:
      - WEBHOOK_URL=http://webhook-receiver:5001/webhook
      - AUTH_TOKEN=your_auth_token_here
    networks:
      - webnet

  webhook-receiver:
    build: ./webhook-receiver
    ports:
      - "5001:5001"
    volumes:
      - ./binary_diff_module/shared_data:/shared
    networks:
      - webnet

  binary-analysis:
    build: ./binary_diff_module
    volumes:
      - ./binary_diff_module/shared_data:/shared
      - ~/.kube/config:/root/.kube/config:ro
      - ./binary_diff_module/kubernetes:/app/kubernetes
    networks:
      - webnet
    depends_on:
      - webhook-receiver
    restart: unless-stopped

  llm-module:
    build: ./LLM_Modules/Llama3.2_11B
    volumes:
      - ./binary_diff_module/shared_data:/shared
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    networks:
      - webnet
    depends_on:
      - binary-analysis
    restart: unless-stopped

  api-service:
    build: ./api_service
    ports:
      - "8000:8000"
    volumes:
      - ./binary_diff_module/shared_data/output:/shared/output
    networks:
      - webnet
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - webnet
    depends_on:
      - api-service
    restart: unless-stopped

networks:
  webnet:
