# myproject/docker-compose.yml

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - webhook-creator
      - webhook-receiver
    networks:
      - webnet

  webhook-creator:
    build: ./webhook-creator
    environment:
      - WEBHOOK_URL=https://fe60-128-210-106-62.ngrok-free.app/webhook
      - AUTH_TOKEN=your_auth_token_here
    networks:
      - webnet

  webhook-receiver:
    build: ./webhook-receiver
    ports:
      - "5001:5001"
    volumes:
      - ./binary_diff_module/shared_data:/shared/binary_diff
      - ./codeql_analysis_module/shared_data:/shared/codeql_analysis
    environment:
      - AUTH_TOKEN=your_auth_token_here
    networks:
      - webnet

  binary-analysis:
    build: ./binary_diff_module
    volumes:
      - ./binary_diff_module/shared_data:/shared/binary_diff
      - ~/.kube/config:/root/.kube/config
      - ./binary_diff_module/kubernetes:/app/kubernetes
    networks:
      - webnet
    restart: unless-stopped

  codeql-analysis:
    build: ./codeql_analysis_module
    volumes:
      - ./codeql_analysis_module/shared_data:/shared/codeql_analysis
      - ~/.kube/config:/root/.kube/config
      - ./codeql_analysis_module/kubernetes:/app/kubernetes
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
