#binary_diff_module/kubernetes/input-output-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: input-output-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
