version: "3"
services:
  ghidra-decompiler:
    container_name: ghidra-decompiler
    image: cincan/ghidra-decompiler
    user: root
    volumes:
      - ./ghidra_scripts:/analysis/scripts
      - ./output:/output
      - ./c_source/version1/main.c:/app/c_source/version1/main.c
      - ./c_source/version2/main.c:/app/c_source/version2/main.c
      - ./input_binaries:/app/input_binaries
    command: >
      decompile /app/input_binaries

  bindiff:
    container_name: bindiff-analyzer
    build:
      context: . # Directory where Dockerfile is located
      dockerfile: Dockerfile.bindiff # The Dockerfile to use
    volumes:
      - ./input_binaries:/app/input_binaries
      - ./diff_results:/app/diff_results
      - ./output:/output
    command: >
      bindiff /app/input_binaries/binary1 /app/input_binaries/binary2 --output=/output/diff_report.txt
