services:
  llm:
    build:
      context: .  # Your build context (current directory)
    image: llama32_11b-llm
    container_name: llm
    volumes:
      - ./input_code.txt:/app/input_code.txt  # Mount files if necessary
      - ./analysis_output.md:/app/analysis_output.md
    environment:
      # Define environment variables for MongoDB URI and other secrets
      HUGGINGFACE_API_TOKEN: ${HUGGINGFACE_API_TOKEN}  # Your Hugging Face API token
      MONGO_URI: ${MONGO_URI}
    command: ["python", "test_llm_module.py", "input_code.txt"]